name: Build and Deploy to Itch.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-webgl:
    name: Build & Deploy WebGL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - WebGL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Unity folders
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/unity3d
            ~/.local/share/unity3d
          key: unity-cache

      - name: Build WebGL with Game CI
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: Pixel Journeys

      - name: Publish to Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
          CHANNEL: ${{ matrix.targetPlatform }}
          ITCH_USER: ${{ secrets.ITCH_IO_USERNAME }}
          ITCH_GAME: ${{ secrets.ITCH_IO_GAME }}
          PACKAGE: Pixel Journeys/build/${{ matrix.targetPlatform }}
