name: Build and Deploy to Itch.io

on:
  push:
    branches:
      - main

jobs:
  buildAndDeploy:
    name: Build WebGL and Deploy to Itch.io
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Unity
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/unity3d
            ~/.local/share/unity3d
          key: Library

      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: Pixel Journeys

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/dl/latest/linux-amd64/butler.zip
          unzip butler.zip -d butler
          chmod +x butler/butler
          sudo mv butler/butler /usr/local/bin/

      - name: Deploy to Itch.io
        run: |
          butler push "Pixel Journeys/build/WebGL" ${{ secrets.ITCH_IO_USERNAME }}/${{ secrets.ITCH_IO_GAME }}:webgl --api-key ${{ secrets.ITCH_IO_API_KEY }}
